### ISSUE TITLE
Not seeing the mark all as complete anymore

### ISSUE THREAD

**Issue by lundeen-bryan** [sagynbek/udemy-plus#1]
This could be my setup as I just reinstalled all my software but... when I go to the udemy course that I'm enrolled in I no longer see the "mark all as complete" button as before. Just to double check it's not blocked is there anywhere other than the local machine that the code resides? I use a ublock clone and although I whitelisted Udemy, if your extension has another site it uses to make it work maybe it is being blocked.

**Comment by lundeen-bryan** [comment]
Just to question again, is there another site where you store procedures other than the chrome extensions folder on the local machine? 
Currently the picture-in-picture works, as well as the keyboard shortcuts for next/previous videos and the video rates. But not the ability to mark sections as complete. This did work until just this week.

**Comment by sagynbek** [comment]
Hello @lundeen-bryan ! It's probably due to change in Udemy html structure, so currently selectors which tries to detect section heading is failing. I've also noticed it couple of days ago. Thanks for report.
I'll not have time for 2-3 weeks, since now extensions require manifest v3. Probably you can wait for update after a month or so. Or you could open PR for update

**Comment by lundeen-bryan** [comment]
Thank you @sagynbek I'll wait for the next update, I appreciate your reply.

**Comment by sagynbek** [comment]
@lundeen-bryan Hopefully it should be fixed with `1.1.0` version. Thanks for reporting
